"""create usermodel

Revision ID: 67b728325696
Revises: fe6f66ac2511
Create Date: 2025-01-16 16:26:35.672245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67b728325696"
down_revision: Union[str, None] = "fe6f66ac2511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hash_password", sa.String(), nullable=False)
    )
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.VARCHAR(), nullable=False))
    op.drop_column("users", "hash_password")
    # ### end Alembic commands ###
